### ISSUE TITLE
IndexError with some audio clips

### ISSUE THREAD

**Issue by ignaciot** [CarlSouthall/ADTLib#10]
Hi there,

Just for some wav files I'm getting the error:

```INFO:tensorflow:Restoring parameters from /Users/ignaciot/miniconda3/lib/python3.6/site-packages/ADTLib/files/KickADTLibAll
INFO:tensorflow:Restoring parameters from /Users/ignaciot/miniconda3/lib/python3.6/site-packages/ADTLib/files/SnareADTLibAll
INFO:tensorflow:Restoring parameters from /Users/ignaciot/miniconda3/lib/python3.6/site-packages/ADTLib/files/HihatADTLibAll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ignaciot/miniconda3/lib/python3.6/site-packages/ADTLib/__init__.py", line 24, in ADT
    Peaks.append(utils.meanPPmm(AFs[j][:,0],PP[j,0],PP[j,1],PP[j,2]))
  File "/Users/ignaciot/miniconda3/lib/python3.6/site-packages/ADTLib/utils/__init__.py", line 44, in meanPPmm
    np.delete(onsets,onsets[i-1+ind])
  File "<__array_function__ internals>", line 6, in delete
  File "/Users/ignaciot/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type
```

Any hints of what might be causing this? These are short clips from songs with a very clearly defined beat pattern.

**Comment by avikj** [comment]
+1, running into the same error

**Comment by jie-chen** [comment]
same here. Could provide audio.

**Comment by matidfk** [comment]
Hey, how did you manage to run this library? I've been trying for ages with no success

**Comment by gorlikariel** [comment]
same @matidfk I'd appreciate if you guys shared how you managed to run it in 2022 @avikj @ignaciot @jie-chen
